# Generated by Django 5.2.4 on 2025-07-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
