# Generated by Django 5.2.4 on 2025-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_registro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='nombre_empleado',
            field=models.CharField(choices=[('Julio', 'Julio'), ('Carlos', 'Carlos'), ('Lucía', 'Lucía')], max_length=100),
        ),
    ]
