# Generated by Django 5.2.4 on 2025-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registro_nombre_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre_empleado',
            field=models.CharField(choices=[('Julio Paredes', 'Julio Paredes'), ('Muhammad Ali', 'Muhammad Ali'), ('Marvin Herlindo Boche Paredes', 'Marvin Herlindo Boche Paredes'), ('Geovanny Sanchez', 'Geovanny Sanchez'), ('Shamir Waseem', 'Shamir Waseem'), ('Eddy Carrillo', 'Eddy Carrillo'), ('Luis Gutierrez', 'Luis Gutierrez'), ('Talal Haider', 'Talal Haider')], max_length=100),
        ),
    ]
